TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += visarCameraIOC.db

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

DB_INSTALLS += $(ASYN)/db/asynRecord.db
#DB_INSTALLS += $(AUTOSAVE)/db/save_restoreStatus.db
#DB_INSTALLS += $(IOCADMIN)/db/iocSoft.db

DB_INSTALLS += $(ADVISARCAMERA)/db/visar.proto

#----------------------------------------------------
# Create and install (or just install)
# Archive files, templates, substitutions like this
#


#----------------------------------------------------
# Create and install (or just install)
# Autosave request files, templates, substitutions like this
#


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

