# Makefile for generic envPaths.
TOP = ../..
IOC = ioc
include $(TOP)/configure/CONFIG
ARCH = linux-x86_64
TARGETS = envPaths

include $(TOP)/configure/RULES.ioc
-include $(TOP)/configure/RULES.archive
-include $(TOP)/configure/RULES.autosave
-include $(TOP)/configure/RULES.copy
